### ISSUE TITLE
label完了但是跑不动

### ISSUE THREAD

**Issue by clark-2468** [7eu7d7/pixiv_AI_crawler#10]
![image](https://user-images.githubusercontent.com/39589318/183833617-eeabc002-5c3a-4c5f-a61a-a6bc0d2aba95.png)

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183834957-dd76a394-89e4-42e0-90a4-203fac2bc781.png)
改了路径跑了一半然后还是报错

**Comment by 7eu7d7** [comment]
某个类别样本数量太少了，不够生成测试集的，你改一下测试集大小n_test

**Comment by clark-2468** [comment]
我怎么知道每个类别有多少个

**Comment by 7eu7d7** [comment]
你更新下代码，我加了先输出每个类别总数的了

**Comment by clark-2468** [comment]
噢我明白了，代码里是3个类别我只有1和0

**Comment by clark-2468** [comment]
话说我6000多张怎么0只有800个1只有280个

**Comment by 7eu7d7** [comment]
> 话说我6000多张怎么0只有800个1只有280个

宽高比超过2.5的会被丢弃，格式不支持打不开的也丢弃

**Comment by clark-2468** [comment]
文件名太长会导致打不开吗，我有4000多张都是jpg啊

**Comment by clark-2468** [comment]
难道是我自己加的代码给整个程序整坏了

**Comment by clark-2468** [comment]
我强制给它改成支持jpeg了`for x in os.listdir(root) if x.lower().endswith('.jpg') or x.lower().endswith('.png') or x.lower().endswith('.jpeg')]`

**Comment by clark-2468** [comment]
话说4000张图片一张一张按也得累死
