### ISSUE TITLE
data_proc.py和训练报错

### ISSUE THREAD

**Issue by RancherJie** [7eu7d7/pixiv_AI_crawler#11]
1. data_proc.py
Traceback (most recent call last):
  File "E:\图片\ai\data_proc.py", line 14, in <module>
    with open(set_raw, 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'imset/cat_7.json'
如果把“dataset.json”改过去会这样
Traceback (most recent call last):
  File "E:\图片\ai\data_proc.py", line 24, in <module>
    data_group[v].append(k)
IndexError: list index out of range

2.不经过data_proc.py，直接训练会这样
   File "E:\图片\ai\train.sh", line 1
    python -m torch.distributed.launch --nproc_per_node=2 main.py \
              ^
SyntaxError: invalid syntax

安装库之类的时候没见到报错之类（非白色文字）的
数据集大约16000个

**Comment by RancherJie** [comment]
还有一个忘写了
labeler.py
def make_label(imgs, save_path, skip=True):
    if skip and os.path.exists(save_path):
        with open(save_path, 'r', encoding='utf8') as f:
            label_dict = json.load(f)
        label_dict_raw=deepcopy(label_dict)
        skiped=set()
    else:
        label_dict={}
        label_dict_raw=deepcopy(label_dict)
        skiped=set()
“else”里自己加了“label_dict_raw=deepcopy(label_dict)  skiped=set()”不然直接运行会报错

ptr=-1
    with tqdm(total=len(imgs)) as pbar:
        while ptr<len(imgs)-1:
            pbar.update(1)
            ptr+=1
            p_img = imgs[ptr]
            p_base=os.path.basename(p_img)

            if skip and (p_base not in skiped) and (p_base in label_dict_raw):
                skiped.add(p_base)
                continue
本地变量"skiped"和“label_dict_raw”没有
初次运行不会有"save_path"存在

**Comment by IrisRainbowNeko** [comment]
看训练教程https://www.bilibili.com/video/BV1YB4y1t7wx/?vd_source=1baf128770b474e3e73b15855df86f48

**Comment by risingsun1412** [comment]
教程寄了

**Comment by RancherJie** [comment]
> 

教程无了

**Comment by RancherJie** [comment]
> 看训练教程 https://www.bilibili.com/video/BV1YB4y1t7wx/?vd_source=1baf128770b474e3e73b15855df86f48

教程无了
