### ISSUE TITLE
timm的版本需要0.4.12？

### ISSUE THREAD

**Issue by clark-2468** [7eu7d7/pixiv_AI_crawler#12]
0.3版本好像会报错因为无法引入一个函数，然后安装0.4.12能解决。requirements里面写的是0.3版本的timm

**Comment by Q78KG** [comment]
> 0.3版本好像会报错因为无法引入一个函数，然后安装0.4.12能解决。requirements里面写的是0.3版本的timm

你可以发一个pr（

**Comment by clark-2468** [comment]
ok

**Comment by IrisRainbowNeko** [comment]
这个0.3是对应pytorch 1.8.2版本的，你是不是装了pytorch其他版本

**Comment by clark-2468** [comment]
啊好像是，我安装torch的时候直接偷懒pip install torch来的，那没事了要是pytorch1.8和timm0.3兼容就行

**Comment by clark-2468** [comment]
我现在环境里的pytorch是1.12的
