### ISSUE TITLE
执行Python train.sh时报错SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by binidx** [7eu7d7/pixiv_AI_crawler#14]
数据集已经全部划分完了，在最后一步训练数据时报错
这是我的train.sh设置：
python -m torch.distributed.launch --nproc_per_node=1 main.py \
--model convnext_tiny --drop_path 0.5 --input_size 384 \
--batch_size 48 --lr 2e-4 --update_freq 2 --nb_classes 5 \
--warmup_epochs 0 --epochs 60 --weight_decay 1e-8  \
--head_init_scale 0.001 --cutmix 0 --mixup 0 \
--save_ckpt_num 100 --dist_eval False \
--color_jitter 0.2 \
--finetune ckpt/checkpoint-best_t5.pth \
--data_path /images_group \
--eval_data_path /images_group \
--imset ./imset/ \
--data_set json \
--output_dir output/tiny6

报错如下：
PS O:\ai\pixiv_AI_crawler-main> python .\train.bat
  File "O:\ai\pixiv_AI_crawler-main\train.bat", line 1
    python -m torch.distributed.launch --nproc_per_node=1 \
              ^
SyntaxError: invalid syntax

**Comment by phourior** [comment]
> 数据集已经全部划分完了，在最后一步训练数据时报错 这是我的train.sh设置： python -m torch.distributed.launch --nproc_per_node=1 main.py --model convnext_tiny --drop_path 0.5 --input_size 384 --batch_size 48 --lr 2e-4 --update_freq 2 --nb_classes 5 --warmup_epochs 0 --epochs 60 --weight_decay 1e-8 --head_init_scale 0.001 --cutmix 0 --mixup 0 --save_ckpt_num 100 --dist_eval False --color_jitter 0.2 --finetune ckpt/checkpoint-best_t5.pth --data_path /images_group --eval_data_path /images_group --imset ./imset/ --data_set json --output_dir output/tiny6
> 
> 报错如下： PS O:\ai\pixiv_AI_crawler-main> python .\train.bat File "O:\ai\pixiv_AI_crawler-main\train.bat", line 1 python -m torch.distributed.launch --nproc_per_node=1 ^ SyntaxError: invalid syntax

你是在colab上跑的吗？如果是的话把train.sh里的内容复制到代码框里，开头加上 ！ 直接运行就行了

**Comment by binidx** [comment]
不是，在Windows11系统下运行的，运行时会报错

**Comment by binidx** [comment]
> > 数据集已经全部划分完了，在最后一步训练数据时报错 这是我的train.sh设置： python -m torch.distributed.launch --nproc_per_node=1 main.py --model convnext_tiny --drop_path 0.5 --input_size 384 --batch_size 48 --lr 2e-4 --update_freq 2 --nb_classes 5 --warmup_epochs 0 --epochs 60 --weight_decay 1e-8 --head_init_scale 0.001 --cutmix 0 --mixup 0 --save_ckpt_num 100 --dist_eval False --color_jitter 0.2 --finetune ckpt/checkpoint-best_t5.pth --data_path /images_group --eval_data_path /images_group --imset ./imset/ --data_set json --output_dir output/tiny6
> > 报错如下： PS O:\ai\pixiv_AI_crawler-main> python .\train.bat File "O:\ai\pixiv_AI_crawler-main\train.bat", line 1 python -m torch.distributed.launch --nproc_per_node=1 ^ SyntaxError: invalid syntax
> 
> 你是在colab上跑的吗？如果是的话把train.sh里的内容复制到代码框里，开头加上 ！ 直接运行就行了

不是，在Windows11系统下运行的，运行时会报错

**Comment by binidx** [comment]
知道了，Windows压根没法训练，或者说这个代码只能运行在Linux环境下，虽然不知道为什么视频教程是在Windows环境演示的。
Python train.sh在Windows下压根没用，把train.sh重命名为train.bat，将\替换成^，然后直接点击train.bat运行，但就算这样Windows还是无法训练，其中一个原因是windows不支持NCCL backend，解决的链接在这（其实没啥用，需要去改conda下载的pyTorch包）：https://blog.csdn.net/StarCap/article/details/120070425
做教程的时候直接指出来吧，还在视频里用Windows演示，很容易误导的，像我这种小白需要折腾好久才能知道原来需要换个环境，考虑过使用colab，但是照片（训练集）就20-30g了，算了吧

**Comment by IrisRainbowNeko** [comment]
> 知道了，Windows压根没法训练，或者说这个代码只能运行在Linux环境下，虽然不知道为什么视频教程是在Windows环境演示的。 Python train.sh在Windows下压根没用，把train.sh重命名为train.bat，将\替换成^，然后直接点击train.bat运行，但就算这样Windows还是无法训练，其中一个原因是windows不支持NCCL backend，解决的链接在这（其实没啥用，需要去改conda下载的pyTorch包）：https://blog.csdn.net/StarCap/article/details/120070425 做教程的时候直接指出来吧，还在视频里用Windows演示，很容易误导的，像我这种小白需要折腾好久才能知道原来需要换个环境，考虑过使用colab，但是照片（训练集）就20-30g了，算了吧

可以装wsl2跑
