### ISSUE TITLE
有关无法将「torch._six」中的「container_abcs」导入之问题

### ISSUE THREAD

**Issue by 42SL** [7eu7d7/pixiv_AI_crawler#19]
AIcrawler.py,line 6,from tim.models import create_model
timm\_init_.py,line2
timm\models\_init_.py,line1

ImportError:cannot import name 'container_abcs' from 'torch._six'

尝试了更换torch版本，但并不起作用

**Comment by IrisRainbowNeko** [comment]
timm版本不对，timm==0.3.2
