### ISSUE TITLE
为什么我跑了半天那个文件夹里一张图片都没有啊

### ISSUE THREAD

**Issue by clark-2468** [7eu7d7/pixiv_AI_crawler#3]

**Comment by clark-2468** [comment]
我感觉事config有问题可否以提供一套具体的参数

**Comment by 7eu7d7** [comment]
运行输出截图看看。这个模型是用我自己数据集训练的，如果是关键词搜索可能你的是被排除的

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183670228-040ee6db-d358-4245-ab20-2270c6e8e19c.png)

**Comment by 7eu7d7** [comment]
看看用户id和cookie配置了没有，vpn代理有没有配置 (http://ip:port)

**Comment by clark-2468** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/39589318/183670339-cf937257-d6a5-4086-a225-9c76a4021dfc.png">
![image](https://user-images.githubusercontent.com/39589318/183670384-560ce938-5b63-4a3f-a78b-ee3860812d2f.png)
![image](https://user-images.githubusercontent.com/39589318/183670485-70b8ac10-63d2-4f00-b2fd-51436fba5897.png)

**Comment by clark-2468** [comment]
我怎么配置代理欸 我登p站不需要vpn也需要添加代理吗

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183670795-1f1e9257-b4bf-46e1-b848-d89b76b08ce2.png)

**Comment by 7eu7d7** [comment]
userid是数字，https://www.pixiv.net/users/  后面的数字

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183670959-38850160-109c-4ad6-818e-ff1ae5424106.png)

**Comment by clark-2468** [comment]
啊这

**Comment by clark-2468** [comment]
我调了半天了还是一点反应都没，甚至没有进入我电脑的流量（网络监控显示）

**Comment by 7eu7d7** [comment]
换个User-Agent试试 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183684867-a00f5578-0517-498e-aa40-228c709a5678.png)

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183685082-b9277e55-528c-4b34-9bcf-f2473ac84346.png)

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183685224-ece9e7ae-f464-498b-bc52-eea07b262102.png)

**Comment by clark-2468** [comment]
这样子还是不行

**Comment by clark-2468** [comment]
`python AIcrawler.py --ckpt C:\Users\31954\pixiv_AI_crawler\ckpt\checkpoint-best_t5.pth  --n_images 300`

这是我用的指令这指令有问题吗

**Comment by 7eu7d7** [comment]
不用代理，那块设置 "PROXY": {}, 试试

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183710547-f72da06d-2cff-4ddc-adda-4d28deba2645.png)

**Comment by clark-2468** [comment]
前面的部分能跑了但是这里报错

**Comment by clark-2468** [comment]
说是数据类型错误

**Comment by Q78KG** [comment]
> 说是数据类型错误

这个可以不用管的，我整了个colab等会传个拉取请求你可以康康

**Comment by Q78KG** [comment]
u1s1这个爬虫爬的图还真不辍

**Comment by Q78KG** [comment]
> 说是数据类型错误
这个问题会中断下载，导致图片没下完程序就结束了。但是你图片要下的少就可以无视（bushi

**Comment by Q78KG** [comment]
> 说是数据类型错误

把--keyword删掉就不会有了

**Comment by clark-2468** [comment]
> > 说是数据类型错误
> 
> 把--keyword删掉就不会有了

可是我指令里没有加keyword啊

**Comment by Q78KG** [comment]
。。。那我就不知道了

**Comment by Q78KG** [comment]
我是直接把代码放在colab上跑的

**Comment by phourior** [comment]
> 我是直接把代码放在colab上跑的

![image](https://user-images.githubusercontent.com/63549341/183822020-44e1b3cc-dfc3-4ca2-a2d2-d38a39e67b2e.png)
您好想请教一下，我也在colab上跑的，但也出现了变量类型错误，请问您遇到过类似情况吗

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183844841-24a2b4c6-bdc5-4705-946e-5e636a2733cb.png)
我也是

**Comment by Q78KG** [comment]
> > 我是直接把代码放在colab上跑的
> 
> ![图像](https://user-images.githubusercontent.com/63549341/183822020-44e1b3cc-dfc3-4ca2-a2d2-d38a39e67b2e.png)您好想请教一下，我也在colab上跑的，但也出现了变量类型错误，请问您遇到过类似情况吗

你这应该是python版本不对，colab默认是py3.7,这个需要3.9，要自己安装py3.9

**Comment by Q78KG** [comment]
> ![图像](https://user-images.githubusercontent.com/39589318/183844841-24a2b4c6-bdc5-4705-946e-5e636a2733cb.png)我也是

这个问题我也有，就是不使用代理之后会弹出来

**Comment by Q78KG** [comment]
> ![图像](https://user-images.githubusercontent.com/39589318/183844841-24a2b4c6-bdc5-4705-946e-5e636a2733cb.png)我也是
如果你有梯子的话你可以用clash开系统代理挂上去

**Comment by Q78KG** [comment]
但是这要在本地电脑运行

**Comment by Q78KG** [comment]
> > 我是直接把代码放在colab上跑的
> 
> ![图像](https://user-images.githubusercontent.com/63549341/183822020-44e1b3cc-dfc3-4ca2-a2d2-d38a39e67b2e.png)您好想请教一下，我也在colab上跑的，但也出现了变量类型错误，请问您遇到过类似情况吗

这个问题我也有，我也没办法解决

**Comment by Q78KG** [comment]
> > 我是直接把代码放在colab上跑的
> 
> ![图像](https://user-images.githubusercontent.com/63549341/183822020-44e1b3cc-dfc3-4ca2-a2d2-d38a39e67b2e.png)您好想请教一下，我也在colab上跑的，但也出现了变量类型错误，请问您遇到过类似情况吗

如果你电脑好就在本地运行挂个clash当代理，这个问题是只要你不用代理就会有的

**Comment by Q78KG** [comment]
我也很纳闷

**Comment by phourior** [comment]
> > > 我是直接把代码放在colab上跑的
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/63549341/183822020-44e1b3cc-dfc3-4ca2-a2d2-d38a39e67b2e.png)您好想请教一下，我也在colab上跑的，但也出现了变量类型错误，请问您遇到过类似情况吗
> 
> 如果你电脑好就在本地运行挂个clash当代理，这个问题是只要你不用代理就会有的

我试着在config.py里把unsuccessful attempt的times提高了，然后就不会报错了。但是我看download_image.py里unsuccessful attempt是有一个自己的try except来抛出异常的

**Comment by Q78KG** [comment]
我也很纳闷为什么会这样

**Comment by Q78KG** [comment]
顺带一提这个仓库是自带一个ipynb的，可以直接用

**Comment by Q78KG** [comment]
这个代理报错的问题只能让Pixiv_crawler的原作者去修

**Comment by Q78KG** [comment]
> > > > 我是直接把代码放在colab上跑的
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/63549341/183822020-44e1b3cc-dfc3-4ca2-a2d2-d38a39e67b2e.png)您好想请教一下，我也在colab上跑的，但也出现了变量类型错误，请问您遇到过类似情况吗
> > 
> > 
> > 如果你电脑好就在本地运行挂个clash当代理，这个问题是只要你不用代理就会有的
> 
> 我试着在config.py里把unsuccessful attempt的times提高了，然后就不会报错了。但是我看download_image.py里unsuccessful attempt是有一个自己的try except来抛出异常的

DOWNLOAD_CONFIG部分

STORE_PATH: 图片保存位置
N_TIMES: 下载失败后的重复请求次数
WITH_TAG: 是否需要抓取标签
FAIL_DELAY: 下载失败后延时（秒）
N_THREAD： 并行下载的线程数量（根据CPU核数调整）⚠️
THREAD_DELAY: 每个线程启动的延时（秒）

应该是在这里设

**Comment by phourior** [comment]
> > > > > 我是直接把代码放在colab上跑的
> > > > 
> > > > 
> > > > ![图像](https://user-images.githubusercontent.com/63549341/183822020-44e1b3cc-dfc3-4ca2-a2d2-d38a39e67b2e.png)您好想请教一下，我也在colab上跑的，但也出现了变量类型错误，请问您遇到过类似情况吗
> > > 
> > > 
> > > 如果你电脑好就在本地运行挂个clash当代理，这个问题是只要你不用代理就会有的
> > 
> > 
> > 我试着在config.py里把unsuccessful attempt的times提高了，然后就不会报错了。但是我看download_image.py里unsuccessful attempt是有一个自己的try except来抛出异常的
> 
> DOWNLOAD_CONFIG部分
> 
> STORE_PATH: 图片保存位置 N_TIMES: 下载失败后的重复请求次数 WITH_TAG: 是否需要抓取标签 FAIL_DELAY: 下载失败后延时（秒） N_THREAD： 并行下载的线程数量（根据CPU核数调整）⚠️ THREAD_DELAY: 每个线程启动的延时（秒）
> 
> 应该是在这里设

![image](https://user-images.githubusercontent.com/63549341/183854673-36241644-7d7e-4fc4-b811-6521646bae9d.png)
是在这里，我改成100后就没报过错了

**Comment by Q78KG** [comment]
FAIL_DELAY再加长逝逝（
我也没有什么好办法

**Comment by clark-2468** [comment]
我就是在国外然后也不需要代理啥的

**Comment by 7eu7d7** [comment]
先根据缩略图判断是否下载大图，如果downloadImage在下载缩略图时候失败，就会返回0，所以把这个当图片加载时候就报错了

**Comment by Q78KG** [comment]
我也是在colab上跑不用代理，我那台小破笔记本能开代理但是配置不行

**Comment by 7eu7d7** [comment]
应该还是网络状况不好导致的，换个网或者多重试几次

**Comment by clark-2468** [comment]
> 先根据缩略图判断是否下载大图，如果downloadImage在下载缩略图时候失败，就会返回0，所以把这个当图片加载时候就报错了

啊？

**Comment by clark-2468** [comment]
所以缩略图为什么下载不下来捏

**Comment by phourior** [comment]
![image](https://user-images.githubusercontent.com/63549341/183855917-f31b476e-9bfb-46c2-a480-69e6d57a9af4.png)
草还真是

**Comment by Q78KG** [comment]
> 应该还是网络状况不好导致的，换个网或者多重试几次

我在下的时候前面几张可以下载但是后面就不行了

**Comment by 7eu7d7** [comment]
> 所以缩略图为什么下载不下来捏

网不行呗，访问超时了

**Comment by clark-2468** [comment]
那直接跳过行不行

**Comment by 7eu7d7** [comment]
> 那直接跳过行不行

可以加上，不够增大超时时间和重试次数也是可以的

**Comment by Q78KG** [comment]
哟西

**Comment by phourior** [comment]
所以提高attempt times其实就是用数量弥补质量了233

**Comment by Q78KG** [comment]
哟西我要不发个pr把配置问题解决了（

**Comment by 7eu7d7** [comment]
> 哟西我要不发个pr把配置问题解决了（

我已经加上了，直接跳过超时的

**Comment by clark-2468** [comment]
啊这

> > 哟西我要不发个pr把配置问题解决了（
> 
> 我已经加上了，直接跳过超时的

**Comment by Q78KG** [comment]
哟西我再逝逝

**Comment by Q78KG** [comment]
既然这个问题已经解决了这个issues也可以关掉了

**Comment by 7eu7d7** [comment]
AI训练教程已经投出去了，快去看
