### ISSUE TITLE
运行的时候报错了，说找不到包

### ISSUE THREAD

**Issue by sirjacky2** [7eu7d7/pixiv_AI_crawler#4]
![QQ截图20220809110551](https://user-images.githubusercontent.com/92053008/183686727-89707f74-672b-409e-8fde-72b1badda0a6.png)
![QQ截图20220809110603](https://user-images.githubusercontent.com/92053008/183686741-decfd0ee-3b12-4975-bd59-fb71067bfe1d.png)
我按着前面的步骤都做了，但是最后这里报错了。
另外想问一下，如果人在国外，需要设置代理么

**Comment by 7eu7d7** [comment]
pytorch版本不对，要安装1.8.2或者1.8.1

**Comment by newton-miku** [comment]
大佬，我和他情况差不多，然后我把pytorch重装成1.8.1了，但是现在报这个错误
![image](https://user-images.githubusercontent.com/29966140/183730747-3d1e46d7-7129-43e6-9534-1acd155fe638.png)
系统是win11 21H2
笔记本是R9000P 2021H

**Comment by newton-miku** [comment]
我的能跑了，需要安装pytorch1.8.2，cudakit需要使用111版本且pytorch必须是==1.8.2+cu111这样的

**Comment by clark-2468** [comment]
> 重装了1.8.2，不报错了，不过运行之后没有下载任何图片 ![QQ截图20220809145036](https://user-images.githubusercontent.com/92053008/183738319-89767460-d5c4-4eda-b226-f1cae4e80f62.png)

我也是这个问题

**Comment by clark-2468** [comment]
用pip安装torch好像就行，直接
`pip install torch`
时代变了pytorch把py给扔了
然后把timm的版本也要改到0.4.12
`pip install timm==0.4.12`
应该可行

**Comment by clark-2468** [comment]
人在国外的话把代理后面那些带着引号一起删了，留着那个大括号就行。我人也在国外

**Comment by clark-2468** [comment]
留着proxy=｛｝，别删多了

**Comment by clark-2468** [comment]
重装182之后没有下载好像就是因为proxy的问题

> 重装了1.8.2，不报错了，不过运行之后没有下载任何图片 ![QQ截图20220809145036](https://user-images.githubusercontent.com/92053008/183738319-89767460-d5c4-4eda-b226-f1cae4e80f62.png)

不下载图片好像就是因为在国外然后proxy拉跨了，国内需要代理服务器的才需要填那个

**Comment by sirjacky2** [comment]
> 重装182之后没有下载好像就是因为proxy的问题
> 
> > 重装了1.8.2，不报错了，不过运行之后没有下载任何图片 ![QQ截图20220809145036](https://user-images.githubusercontent.com/92053008/183738319-89767460-d5c4-4eda-b226-f1cae4e80f62.png)
> 
> 不下载图片好像就是因为在国外然后proxy拉跨了，国内需要代理服务器的才需要填那个

OK果然是这个原因，解决了，感谢
