### ISSUE TITLE
训练模型的数据初始化报错

### ISSUE THREAD

**Issue by clark-2468** [7eu7d7/pixiv_AI_crawler#7]
![image](https://user-images.githubusercontent.com/39589318/183755373-cac4b96a-a8a9-401a-b6cc-a63c80d1adeb.png)

**Comment by clark-2468** [comment]
好像是Unicode找不到解码器还是找不到编码器

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183755455-18c3674d-eda5-4a6f-8f78-6c02e30e1a11.png)
labeler.py和data_proc.py里的utf8被我都改成utf-8了也还是这样

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183755675-2d07f918-b437-4ea6-b98f-f95805db8abe.png)
是我路径有问题吗

**Comment by 7eu7d7** [comment]
你路径里有\ ，需要在字符串前面加r，或者把 \ 改成 /
