### ISSUE TITLE
在colab上爬取时无法download

### ISSUE THREAD

**Issue by phourior** [7eu7d7/pixiv_AI_crawler#8]
![image](https://user-images.githubusercontent.com/63549341/183800007-1ff6bd72-e7f0-4897-80bb-e9fe5586b50d.png)
已经把proxy的内容去掉了，还是无法下载

**Comment by 7eu7d7** [comment]
等一会，可能下载速度慢，已经到下载步骤了

**Comment by phourior** [comment]
> 等一会，可能下载速度慢，已经到下载步骤了

谢谢解答

**Comment by phourior** [comment]
> 等一会，可能下载速度慢，已经到下载步骤了

但是我看cell里运行已经结束了，不像是在下载的样子

**Comment by 7eu7d7** [comment]
> > 等一会，可能下载速度慢，已经到下载步骤了
> 
> 但是我看cell里运行已经结束了，不像是在下载的样子

这个^C是程序被强制终止了，你按什么了吧

**Comment by phourior** [comment]
> > > 等一会，可能下载速度慢，已经到下载步骤了
> > 
> > 
> > 但是我看cell里运行已经结束了，不像是在下载的样子
> 
> 这个^C是程序被强制终止了，你按什么了吧

我什么都没按，每次都是到了downloading后自动终止的

**Comment by phourior** [comment]
我在stackoverflow上查到^c多半是ram超了，请问您有相关的解决办法吗

**Comment by phourior** [comment]
我重新申请了一个设备，这次没有自动终止了，但出现了变量类型错误，如图所示
![image](https://user-images.githubusercontent.com/63549341/183817945-94d89d01-60b2-49ed-bee3-cf22199d9c2a.png)

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183916346-87700d9e-8a66-4004-9357-74057377c367.png)
是我网络不行还是我CPU不行还是我拿的数据量太多了我跑了快一个下午了

**Comment by phourior** [comment]
> ![image](https://user-images.githubusercontent.com/39589318/183916346-87700d9e-8a66-4004-9357-74057377c367.png) 是我网络不行还是我CPU不行还是我拿的数据量太多了我跑了快一个下午了

应该就是单纯响应慢，我在colab上跑也是差不多1item/s

**Comment by clark-2468** [comment]
> > ![image](https://user-images.githubusercontent.com/39589318/183916346-87700d9e-8a66-4004-9357-74057377c367.png) 是我网络不行还是我CPU不行还是我拿的数据量太多了我跑了快一个下午了
> 
> 应该就是单纯响应慢，我在colab上跑也是差不多1item/s

我裂开辣，colab上面可以一直挂着吗，我电脑不能晚上开机

**Comment by phourior** [comment]
colab得保持浏览器打开，好像没法关机运行

**Comment by clark-2468** [comment]
挂个日本的vpn会不会有帮助呢

**Comment by clark-2468** [comment]
vpn给的加密会不会让过程更慢啊

**Comment by phourior** [comment]
我不太清楚，你可以尝试一下，不过感觉应该差距不大。挂vpn的时候，记得在config.py里的proxy把https对应的端口填进去

**Comment by clark-2468** [comment]
vpn的原理是把本机的ip变成服务器的ip吧，本机ip就是了还要用服务器的那个ip吗，再说了我也不知道服务器ip是啥端口号多少

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/183964895-861cd0a1-e312-4711-ac6c-8280879bf435.png)
总算跑完力，跑了我5个小时

**Comment by clark-2468** [comment]
![image](https://user-images.githubusercontent.com/39589318/184098449-80971d3b-f3b0-4196-a8b2-7238aed82ba6.png)
colab有8it/s

> > ![image](https://user-images.githubusercontent.com/39589318/183916346-87700d9e-8a66-4004-9357-74057377c367.png) 是我网络不行还是我CPU不行还是我拿的数据量太多了我跑了快一个下午了
> 
> 应该就是单纯响应慢，我在colab上跑也是差不多1item/s

**Comment by phourior** [comment]
> ![image](https://user-images.githubusercontent.com/39589318/184098449-80971d3b-f3b0-4196-a8b2-7238aed82ba6.png) colab有8it/s
> 
> > > ![image](https://user-images.githubusercontent.com/39589318/183916346-87700d9e-8a66-4004-9357-74057377c367.png) 是我网络不行还是我CPU不行还是我拿的数据量太多了我跑了快一个下午了
> > 
> > 
> > 应该就是单纯响应慢，我在colab上跑也是差不多1item/s

![1660214887597](https://user-images.githubusercontent.com/63549341/184117549-8deab857-1b1d-489b-ac09-859990a7dadf.png)
很怪，我又跑了一遍还是只有1.92，可能是因为我没有更新download_images.py跳过失败图片，还是用的增加重试次数导致速度很慢

**Comment by clark-2468** [comment]
你直接从github代码库里的ipynb进入colab然后做个copy，GitHub上提供的是傻瓜式按按钮安装

**Comment by clark-2468** [comment]
哦对了googledrive容忍H图吗？

**Comment by phourior** [comment]
我把训练集直接挂在google drive上的，目前看上去是容忍的

**Comment by clark-2468** [comment]
> 我把训练集直接挂在google drive上的，目前看上去是容忍的

那我放心了
